# Generated by Django 4.1.3 on 2022-11-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fnumber', models.IntegerField(blank=True, null=True)),
                ('fdate', models.DateField()),
                ('ftime', models.TimeField()),
                ('price', models.FloatField()),
                ('class_field', models.IntegerField(db_column='class')),
                ('capacity', models.IntegerField()),
                ('available', models.IntegerField()),
                ('dest', models.ForeignKey(db_column='dest', on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('orig', models.ForeignKey(db_column='orig', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='main.city')),
            ],
            options={
                'db_table': 'Flight',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ordernum', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('cardnum', models.CharField(max_length=16)),
                ('cardmonth', models.IntegerField()),
                ('cardyear', models.IntegerField()),
                ('order_date', models.DateField(blank=True, null=True)),
                ('cid', models.ForeignKey(db_column='cid', on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('dfid', models.ForeignKey(db_column='dfid', on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='main.flight')),
                ('rfid', models.ForeignKey(blank=True, db_column='rfid', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.flight')),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
    ]
